### ISSUE TITLE
wrong reputation presentation 

### ISSUE THREAD

**Issue by orenyodfat** [daostack/alchemy#1332] opened 2020-01-27 10:12 UTC
The issue appears on "Safari" browser 
![Screen Shot 2020-01-27 at 10 54 58](https://user-images.githubusercontent.com/5994398/73166319-4f07bf00-40fe-11ea-863c-f6e9de707ab1.png)

**Comment by tibetsprague** [comment] 2020-02-06 03:06
i don't believe we officially support Safari. @A-Zak ?

**Comment by dkent600** [comment] 2020-02-06 12:15
> i don't believe we officially support Safari. @A-Zak ?

That is my understanding as well

**Comment by dkent600** [comment] 2020-02-10 22:25
@orenyodfat Can you please supply a URL that will demonstrate this problem?

**Comment by dkent600** [comment] 2020-02-10 22:25
Safari or not, I think we should at least understand why this is happening.

**Comment by dkent600** [comment] 2020-02-11 16:44
@jellegerbrandy  The cause of this is not evident.  I don't have a means of reproducing it on my desktop where I could easily experiment with the css.  The css+html in this spot (and in the proposal cards in general) really needs to be refactored, but I am not sure this particular issue is worth spending time on now, so I recommend closing this.

**Comment by jellegerbrandy** [comment] 2020-02-20 10:34
ok, thanks @dkent600 

"closing because we do not support safari"

**Closed by jellegerbrandy** 2020-02-20 10:34 UTC
Labels: Blocked, UI, UX
