### ISSUE TITLE
package-lock.json needs to be refreshed and dependencies fixed

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#1321] opened 2020-01-21 22:57 UTC
package-lock.json is out-of-date.  Further, after refreshing the build breaks with:

> ERROR in ./node_modules/ipfs-bitswap/src/types/message/index.js
Module not found: Error: Can't resolve 'multicodec/src/name-table' in 'C:\Users\dkent\Documents\Projects\GitHub\DAOStack\alchemy\node_modules\ipfs-bitswap\src\types\message'
 @ ./node_modules/ipfs-bitswap/src/types/message/index.js 10:18-54
 @ ./node_modules/ipfs-bitswap/src/want-manager/index.js
 @ ./node_modules/ipfs-bitswap/src/index.js
 @ ./node_modules/ipfs/src/core/components/start.js
 @ ./node_modules/ipfs/src/core/components/index.js
 @ ./node_modules/ipfs/src/core/index.js
 @ ./node_modules/3box/lib/3box.js

See also https://github.com/daostack/alchemy/issues/1320

**Comment by dkent600** [comment] 2020-01-22 00:52
Here is the solution, which I've implemented in the Competition branch:

https://github.com/3box/3box-js/issues/687#issuecomment-573445395

Make sure the package.json entry looks like this (pegged version):

> "multicodec": "0.5.6",

**Comment by jellegerbrandy** [comment] 2020-01-23 08:36
It seems the problem is purely yours: builds are working on travis and for me locally. Closing this, plz reopen if I misunderstood.

**Comment by dkent600** [comment] 2020-01-23 10:31
Travis doesn't delete the package-loc.json file.  Did you when you tried?

**Comment by jellegerbrandy** [comment] 2020-01-24 14:38
No I did not delete package-lock. And neither should you, I think :-) 

In any case, seems a bug in the3box package, and it seems you solved it  by pinning the multicodec version.

Not sure what further action is required, so I'm closing this again.

**Closed by jellegerbrandy** 2020-01-24 14:38 UTC
