### ISSUE TITLE
support the xdai network

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#1363] opened 2020-02-03 14:50 UTC
We'd like to support the xdai network. This means:

- [x] connect to xdai eth provider and subgraph
- [x] make "xdai" settable by an ENV variable (next to rinkeby, main and ganache)
- [x] add network check for xdai (in the same way we do now for main and rinkeby)
- [x] check wallet support (should not be a problem, but we need to check if all wallets will continue to work) [just using metamask and burner on the xdai version]
- [x] dao balances are not happy: 
![image](https://user-images.githubusercontent.com/1306173/72543212-b06d9980-3885-11ea-924e-3fde4fc685e1.png) [fixed the endpoint, so "eth" balance si read correctly, GEN does not exist on xdai network yet, but when it does it should just work]
- [x]  all references to "ETH" should become xDAI (??) (for example, re the contributionreward)
- [x] all references to "GEN" should become xGEN
- [x] I have not managed to vote ("voting is disabled") even if an account does have rep 
- [x] we should not look for token balances for non-existing tokens int he xdai network (i.e. we should make `tokens.json` depend on the network)

**Comment by tibetsprague** [comment] 2020-02-03 19:43
Is this a duplicate of #1311 ?

**Comment by jellegerbrandy** [comment] 2020-02-04 12:00
it is a dupe, i've closed #1311 and edited this one

**Comment by jellegerbrandy** [comment] 2020-02-04 12:00
Futher dev int he `xdai-support` branch

**Comment by tibetsprague** [comment] 2020-02-06 02:30
so now work off the competitions branch?

**Closed** 2020-02-07 08:08 UTC
Labels: EthDenver/Competition
