### ISSUE TITLE
Can't stake on staging - tx error

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#436] opened 2019-03-17 07:44 UTC
When trying to stake on staging, the ends with an error /:

e.g. tx:
https://rinkeby.etherscan.io/tx/0xfc9d750832902121b97c08305f7c2794a14acb0a5d06452c519e1d386aeb9477

**Comment by jellegerbrandy** [comment] 2019-03-18 09:00
please provide some more info? Which DAO? Whch proposal? Do you have a link?

**Comment by A-Zak** [comment] 2019-03-27 08:42
Latest update - tx seem to be right, problems probably come from the subgraph crashing and not reporting properly to alchemy.

**Comment by jellegerbrandy** [comment] 2019-03-27 10:40
The transaction is "right" in the sense that it was supposed to revert, but there is a Big Bug here: alchemy is just reporting a generic error, not an explanatino of that error. Cf. also this issue https://github.com/daostack/client/issues/155

**Comment by tibetsprague** [comment] 2019-03-27 17:21
Do we have a reproducible situation here that we can test locally and setup better error handling for?

**Comment by jellegerbrandy** [comment] 2019-03-28 14:50
I'm closing this issue. Staking works on staging.

The cause here was two-fold:

(a) the subgraph stopped indedxing, so we were enabled the staking button even though it should not. If the subgraph (or another service) is not working, this is not in any way noted or reported by alchemy. There is an issue https://github.com/daostack/alchemy/issues/345 that should mitigate that.

(b) The error reporting was very generic, and so the cause was hard to pin down. This is a client issue: https://github.com/daostack/client/issues/155

**Closed by jellegerbrandy** 2019-03-28 14:50 UTC
Labels: bug
