### ISSUE TITLE
Set profile page is not display if click from within proposal

### ISSUE THREAD

**Issue by peculiarity** [daostack/alchemy#996] opened 2019-08-01 08:13 UTC
OS: Linux
Chrome: 74.0.37...

I'm a new user ( haven't participated in anything )

Visited the following [proposal](https://alchemy.daostack.io/dao/0x519b70055af55a007110b4ff99b0ea33071c720a/proposal/0x9c5e2ea7878c3e721f431b77d7e5eda45baed3164a2da0e660d21deb5cbb95c3)

- Hovered my address ( top right corner ) and saw that I can see my full profile. ( at the bottom of the popup window there is - ( **This member is not found** )
- Clicked on `full profile` and it displayed the following thing.
 ![image](https://user-images.githubusercontent.com/23715025/62276570-a32e3100-b444-11e9-9e3a-1a097bffba99.png)

Returned to home page ( https://alchemy.daostack.io ).

-  Hovered on my address - no **This member is not found** message any more
- Clicked on `full profile` and it redirected me to a page where I can setup my profile.

**Expected behavior:** If the user needs to create a profile and doesn't have one, they should be able to get to the profile page from any other page not just from home page.

**Comment by tibetsprague** [comment] 2019-09-11 22:26
@peculiarity i cannot reproduce this, how are you connecting, through metamask or another wallet?

**Comment by peculiarity** [comment] 2019-09-25 19:59
Metamask

**Comment by jellegerbrandy** [comment] 2019-10-14 11:40
i cannot reproduce this either. Closing the issue.

**Closed by jellegerbrandy** 2019-10-14 11:40 UTC
