### ISSUE TITLE
Have a link to our telegram chat from the alchemy interface

### ISSUE THREAD

**Issue by arsena21** [daostack/alchemy#2271] opened 2020-11-18 17:42 UTC
Often times, getting response from zendesk is a pain. People have a quick question and it would be better to just send them to a chat. Maybe we can have a telegram icon or discord link somewhere.... pretty low hanging fruit and should help in our community building efforts.

**Comment by Razzwan** [comment] 2020-11-23 14:35
Looks like this is duplicate of https://github.com/daostack/alchemy/issues/2246

**Closed** 2020-11-30 20:38 UTC
