### ISSUE TITLE
Proposals are not executing in the UI

### ISSUE THREAD

**Issue by pat-daostack** [daostack/alchemy#1123] opened 2019-09-15 12:11 UTC
Seems to be a new bug: proposals are not being executed ... all five at the top of GenDAO atm should be gone and available to redeem but nothing is happening in the UI when execute button is clicked.

![propsoals not executing](https://user-images.githubusercontent.com/42677601/64921358-ab5ae980-d7c2-11e9-9844-df0ea5f00f12.PNG)

**Comment by dkent600** [comment] 2019-09-15 13:39
@pat-daostack What happens when you refresh the page?

**Comment by jellegerbrandy** [comment] 2019-09-20 10:32
This is our bot failing. It seems fixed now.

**Closed by jellegerbrandy** 2019-09-20 10:32 UTC

**Comment by dkent600** [comment] 2019-09-20 13:19
@jellegerbrandy What does the bot have to do with clicking the execute button in the UI?

**Comment by jellegerbrandy** [comment] 2019-09-20 13:55
Sorry, I answered to quickly and did not type what I thought :-)

it was our subgraph failing to update, so these proposals timed out and "nothing happened" after executing them. And this is fixed now.

**Comment by tibetsprague** [comment] 2019-09-20 20:51
I still think we should get this working locally and on Rinkeby where we don't have bots as much as we can

**Comment by tibetsprague** [comment] 2019-09-20 20:51
and as a backup

**Comment by jellegerbrandy** [comment] 2019-09-24 06:44
@tibetsprague the cause of this issue was not "there is a bug in alchemy so that execute does not work" but "the subgraph stopped indexing so it seemed that the execute button did not work (But instead it probably worked, except that alchemy did not update)"

if you believe it is broken after all, open another issue?
