### ISSUE TITLE
Show a little notification while waiting for the user to sign a tx

### ISSUE THREAD

**Issue by A-Zak** [daostack/alchemy#512] opened 2019-03-28 19:46 UTC
Sometimes MM isn't popping up, so nothing seems to be happening. we're waiting for the user, but she doesn't know about it O_O

**Comment by jellegerbrandy** [comment] 2019-03-29 12:01
What is "a little notification"?

**Comment by jellegerbrandy** [comment] 2019-03-29 12:17
What I mean is that, yes, clearly, there is a hole in the notification flow of the transaction, and we should think of how to handle this.

- User clicks send. Show notification "[Vote/Stake/Whatever] transaction sent! Please wait for it to be processed". Disable the button (:arrow_left: this is superimportant) and perhaps show a litte loading spinner on the button. 
- On mined, show notification "XXX transactino processed succesfully"
- On 3 confirmations, show "XX transation confirmed" (but we can omit this)
- On error, show an error, if possible explaining the cause ("cannot vote bc proposal expired")

This 3 confirmations are already being shown, code is here: https://github.com/daostack/alchemy/blob/dev/src/actions/arcActions.ts#L166

I **suppose** you are proposign to insert a 4th notification, before all the others, saying "opening metamask" or something (I don't know, you did not say), which is nice if MM is slow to open, and just confusing if MM opens before the notification happens.

Button disabling is not there, I think it is essential.

**Comment by tibetsprague** [comment] 2019-04-01 05:02
disabling the button and having a spinner is the most important aspect of this

**Comment by A-Zak** [comment] 2019-04-02 17:22
There is a different issue for disabling the buttons.
This one is about what Jelle said, adding a notification saying "XXX transaction waiting for signature" before each transaction just to make sure that the user knows that something happened.

**Comment by jellegerbrandy** [comment] 2019-04-03 08:29
No, that is NOT what I said. 

I think adding this notification is not such a good idea, because (a) we do not kow how fast/slow MM is on the users computer, so the message might be just as easily confuse the user if MM opens before we show the message and (b) we do not need the message if we disable teh button and show the spinner.

I'm in favor of closing this now

**Comment by A-Zak** [comment] 2019-04-03 19:55
Spinners over buttons is not a simple solution. we need to find a proper spinner that will work in place of all the buttons which is not an easy task. And also implementing it should not be as straightforward as just replace the button with a spinner - this would work in some cases but not in all.

I prefer to disable the buttons and show a notification over having a spinner in place of the button - at least for now. I agree that it is not the best solution, but for now, it is better.  :)

Also, the notification should always appear before MM, because it's synchronous, and MM isn't :)

**Comment by jellegerbrandy** [comment] 2019-04-05 09:01
Its not synchronous.

**Comment by A-Zak** [comment] 2019-04-09 23:53
Sorry, I assumed it would be... but still it has to have an advantage over metamask... since it is a user-initiated action, everything that happens inside this event loop should happen first...
no?

**Comment by jellegerbrandy** [comment] 2019-04-16 15:22
no, I don't think you can count on that :)

**Comment by tibetsprague** [comment] 2019-04-17 04:45
this is actually a pretty complicated thing to figure out, basically we either need to bring back a Redux state that tracks all the current transactions and associates them with proposals, or the client library needs to track this and give us the current transaction states for each proposal, which would be easier since we currently get all the state from the client subscriptions. lets discuss @jellegerbrandy

**Closed** 2019-05-15 08:04 UTC
