### ISSUE TITLE
submit button on transactions should be disabled after click

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/alchemy#344] opened 2019-03-05 14:36 UTC
Sometimes, MM is reacting slowly, and so you will click several times on the submit button. When MM then "wakes up", you will get a confirmation window for each time clicked, and so will perform the same action again and again. 

The button should instead be disabled until the tx is sent.

**Comment by A-Zak** [comment] 2019-03-11 23:05
All action buttons should be disabled while waiting...

**Comment by tibetsprague** [comment] 2019-04-01 16:55
stay disabled until transaction confirmed

**Comment by A-Zak** [comment] 2019-04-02 17:22
💪

**Comment by jellegerbrandy** [comment] 2019-04-03 08:32
Very very cool. 

(1) I think it should be dsiabled until transaction sent (i.e. after clikcing ok on MM), not until confirmed. Think of the "create proposal" button, why do I need to wait for the tx to be confirmed to create another one?

(2) Can we show a spinner, to make clear that the button is not really disabled, but rather waiting for something?

(3) What is the subscription somehow breaks, and we never get the confirmation. Will the button be disabled forever, or is there also a natural timeout after which it is enabled again?

**Comment by brodeur** [comment] 2019-04-03 17:54
For me: Add spinners as a class state (if class, show spinner & halftone)

**Comment by A-Zak** [comment] 2019-04-03 19:40
@jellegerbrandy - right, that is what I meant - stay disabled until tx sent... #languageIsImportant...

@brodeur please wait with the spinners. we have a couple of more important things to do atm, and also, we need to find a spinner that will work on all buttons... :)

**Comment by tibetsprague** [comment] 2019-04-17 04:34
so im actually having a hard time figuring out where this might happen. all the action buttons bring up the pre transaction modal, and then clicking submit in that modal immediately closes the modal, so which buttons exactly do we have issues with...

**Comment by A-Zak** [comment] 2019-04-18 15:55
Can't reproduce anymore, closing for now

**Closed by A-Zak** 2019-04-18 15:55 UTC
Labels: Small, nth - v1 genesis
