### ISSUE TITLE
Defaults params are submitted when creating proposals

### ISSUE THREAD

**Issue by roienatan** [daostack/alchemy#2115] opened 2020-09-10 16:23 UTC
The defaults params that are stored in the session storage are submitted even when modifying them.

**Comment by dkent600** [comment] 2020-09-10 17:08
@roienatan is referring to the Create Proposal modal:

1. input some values into any Create Proposal modal
1. close the modal without submitting
1. reopen the modal
1. modify one of the cached values
1. submit the proposal

RESULT:
The cached value is used to create the proposal

EXPECT:
The modified value to be used to create the proposal

**Comment by dkent600** [comment] 2020-09-11 13:16
@roienatan Using ContributionReward, I am unable to reproduce this problem.  Can you please recheck and either close this or give more specific steps? Thanks!

**Comment by roienatan** [comment] 2020-09-11 15:16
> @roienatan Using ContributionReward, I am unable to reproduce this problem. Can you please recheck and either close this or give more specific steps? Thanks!

I encountered this issue on Plugin Manager proposal

**Comment by roienatan** [comment] 2020-09-11 16:13
Steps to reproduce:
1. Go to Plugin Manager
2. Click the Create Proposal button
3. Choose Plugin Manager under `Plugin to add`
4. Change any value under Plugin to add
5. Submit the proposal
6. Go to proposal summary
Result: The value that you change has the original default value.
Expect: The value you provided.

**Closed** 2020-09-11 18:41 UTC
Labels: 2.0
