### ISSUE TITLE
can't view History in readonly mode with no provider

### ISSUE THREAD

**Issue by dkent600** [daostack/alchemy#945] opened 2019-07-19 10:18 UTC
STEPS:

1. disable provider extensions (MM, Safe).
2. Go to https://alchemy.daostack.io/dao
3. then select a DAO (I selected dxDAO)
4. then Click on the "History" menu item

EXPECT:
I expect to be able to view the page.  The default Web3 provider (via Infura) should be sufficient.

ACTUAL RESULT:
I am stuck on "Loading...".

In the console:

```
Using default Web3 (read-only) provider
app.bundle-030430a7.js (70,19377)

MM not available or not set correctly: using default web3 provider:  Please install or enable Metamask or Gnosis Safe
app.bundle-030430a7.js (70,19377)

4SCRIPT12030: SCRIPT12030: WebSocket Error: Network Error 12030, The connection with the server was terminated abnormally
```

**Comment by dkent600** [comment] 2019-07-19 10:28
Hmm, it only happened the first time I tried.  The second time it worked OK.

**Comment by dkent600** [comment] 2019-07-22 19:45
![image](https://user-images.githubusercontent.com/1821666/61660405-bc421f80-ac97-11e9-84b2-a3b3c29fb40c.png)

**Comment by jellegerbrandy** [comment] 2019-10-10 08:20
I cannot reproduce this, is this fixed?
Closing this, please re-open if it is still relevant

**Closed by jellegerbrandy** 2019-10-10 08:20 UTC
