### ISSUE TITLE
Display/css issues in the bottom right

### ISSUE THREAD

**Issue by EzraWeller** [daostack/alchemy#1548] opened 2020-03-31 13:12 UTC
I am seeing some visual overlaps in the bottom right menus of Alchemy (support links + DAO holdings). I'm also finding the bottom of the links menu is out of the display of my browser (can't scroll to see it). This is on Mac/Chrome.

<img width="1253" alt="Bottom left wont scroll" src="https://user-images.githubusercontent.com/5414803/78029910-4f574d00-732f-11ea-9755-a15bfc3f36ae.png">
<img width="443" alt="Further broken display" src="https://user-images.githubusercontent.com/5414803/78029918-51b9a700-732f-11ea-9ff4-749077a41b2f.png">
<img width="292" alt="More broken display" src="https://user-images.githubusercontent.com/5414803/78029925-541c0100-732f-11ea-83c3-a1df74a0d75a.png">

**Comment by tibetsprague** [comment] 2020-03-31 22:01
somewhat of a dupe of https://github.com/daostack/alchemy/issues/1505

**Comment by roienatan** [comment] 2020-12-28 19:40
Solved except of this https://github.com/daostack/alchemy/issues/2379

**Closed by roienatan** 2020-12-28 19:40 UTC
